-- Safe, idempotent migration: Lottery page, Hockey seed, store hours, inventory sort_order.
-- Uses CREATE TABLE IF NOT EXISTS / ADD COLUMN IF NOT EXISTS / conditional seeds only.
-- Does not delete or overwrite existing production rows.

-- ---------------------------------------------------------------------------
-- Store hours on the singleton settings row (admin-editable)
-- Opening stays 7:30 AM; closing defaults to 9:00 PM (including Sunday).
-- ---------------------------------------------------------------------------
ALTER TABLE settings ADD COLUMN IF NOT EXISTS weekday_days TEXT NOT NULL DEFAULT 'Monday – Saturday';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS weekday_open TEXT NOT NULL DEFAULT '7:30 AM';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS weekday_close TEXT NOT NULL DEFAULT '9:00 PM';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS sunday_days TEXT NOT NULL DEFAULT 'Sunday';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS sunday_open TEXT NOT NULL DEFAULT '7:30 AM';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS sunday_close TEXT NOT NULL DEFAULT '9:00 PM';

-- Ensure closing times are 9:00 PM without touching opening hours.
UPDATE settings
SET weekday_close = '9:00 PM',
    sunday_close = '9:00 PM'
WHERE id = 1;

-- ---------------------------------------------------------------------------
-- Inventory display order (for admin reorder)
-- ---------------------------------------------------------------------------
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS inventory_sort_order_idx ON inventory (sort_order);

-- ---------------------------------------------------------------------------
-- Lottery page (singleton) + sections
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lottery_page (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  visible BOOLEAN NOT NULL DEFAULT TRUE,
  title TEXT NOT NULL DEFAULT 'Lottery',
  subtitle TEXT NOT NULL DEFAULT 'New York Lottery',
  description TEXT NOT NULL DEFAULT 'Play New York Lottery games in-store at Prabhu Cards & Gifts. Scratch-offs, draw games, and more — ask our team for current jackpots and tickets.',
  disclaimer TEXT NOT NULL DEFAULT 'Must be 18 years or older to purchase lottery tickets. Please play responsibly.',
  hero_image_url TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS lottery_sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  image_url TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  visible BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS lottery_sections_sort_order_idx ON lottery_sections (sort_order);
CREATE INDEX IF NOT EXISTS lottery_sections_visible_idx ON lottery_sections (visible);

-- Seed lottery page only if missing
INSERT INTO lottery_page (id, visible, title, subtitle, description, disclaimer, hero_image_url, updated_at)
VALUES (
  1,
  TRUE,
  'Lottery',
  'New York Lottery',
  'Play New York Lottery games in-store at Prabhu Cards & Gifts. Scratch-offs, draw games, and more — ask our team for current jackpots and tickets.',
  'Must be 18 years or older to purchase lottery tickets. Please play responsibly.',
  'https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3?w=1920&q=80',
  NOW()
)
ON CONFLICT (id) DO NOTHING;

-- Seed default lottery sections only when the table is empty
INSERT INTO lottery_sections (title, description, image_url, sort_order, visible, created_at)
SELECT v.title, v.description, v.image_url, v.sort_order, TRUE, NOW()
FROM (
  VALUES
    (
      'Scratch-Off Tickets',
      'Browse a wide selection of New York Lottery scratch-off tickets with prizes for every budget. New games arrive regularly — stop in to see what''s available.',
      'https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3?w=800&q=80',
      0
    ),
    (
      'Draw Games',
      'Play popular draw games including Powerball, Mega Millions, Cash4Life, and other New York Lottery favorites. Ask in-store for current jackpots and drawing schedules.',
      'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&q=80',
      1
    ),
    (
      'In-Store Convenience',
      'Pick up lottery tickets while you shop for cards, gifts, and collectibles. Friendly service and quick checkout make it easy.',
      'https://images.unsplash.com/photo-1556740749-887f6717d7e4?w=800&q=80',
      2
    )
) AS v(title, description, image_url, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM lottery_sections LIMIT 1);

-- ---------------------------------------------------------------------------
-- Seed Hockey Trading Cards category product only if none exists
-- ---------------------------------------------------------------------------
INSERT INTO inventory (
  name, description, image_url, subcategory, sport_type, price, in_stock, sort_order, created_at
)
SELECT
  'Hockey Cards',
  'Browse hockey trading cards featuring NHL stars, rookies, hobby boxes, packs, and collectible singles.',
  'https://images.unsplash.com/photo-1515703407324-5f753afd8be8?w=800&q=80',
  'trading-cards',
  'hockey',
  NULL,
  TRUE,
  0,
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM inventory
  WHERE subcategory = 'trading-cards' AND sport_type = 'hockey'
);
